cc_library(
    name = 'cache',
    srcs = [
        'cache.cc',
        'hr_cache.cc'
    ],
    deps = [
        '//proto:status_code_proto',
        '//toft/base/string:string',
        '//toft/system/threading:threading',
        '//thirdparty/glog:glog'
    ],
     link_all_symbols=True
)
