cc_library(
    name = 'key_coding',
    srcs = 'key_coding.cc',
    deps = [
        '//toft/base/string:string'
    ]
)

cc_test(
    name = 'key_coding_test',
    srcs = 'key_coding_test.cc',
    deps = [
        ':key_coding',
        '//toft/base/string:string',
        '//thirdparty/gtest:gtest'
    ]
)
