cc_library(
    name = 'kv_base',
    srcs = [
        'kv_base.cc',
        'leveldb_base.cc'
    ],
    deps = [
        '//proto:status_code_proto',
        '//thirdparty/leveldb:leveldb',
        '//toft/system/threading:threading',
        '//toft/base/string:string'
    ]
)
