cc_library(
    name = 'schema_utils',
    srcs = [
        'schema_utils.cc',
        'prop_tree.cc'
    ],
    deps = [
        '//engine:engine_flags',
        '//engine:tablet_schema_proto',
        '//toft/base/string:string'
    ]
)
